// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcBootstrap_CoreMvc.Models;

namespace MvcBootstrap_CoreMvc.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("MvcBootstrap_CoreMvc.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "RD",
                            Email = "no@gmail.com",
                            Mobile = "0912-422231",
                            Name = "Kevin",
                            Title = "專員"
                        },
                        new
                        {
                            Id = 2,
                            Department = "RD",
                            Email = "no@gmail.com",
                            Mobile = "0912-422231",
                            Name = "Lissa",
                            Title = "助理"
                        },
                        new
                        {
                            Id = 3,
                            Department = "RD",
                            Email = "no@gmail.com",
                            Mobile = "0912-422231",
                            Name = "Sheldon",
                            Title = "老闆"
                        },
                        new
                        {
                            Id = 4,
                            Department = "RD",
                            Email = "no@gmail.com",
                            Mobile = "0912-422231",
                            Name = "Amy",
                            Title = "客服"
                        },
                        new
                        {
                            Id = 5,
                            Department = "RD",
                            Email = "no@gmail.com",
                            Mobile = "0912-422231",
                            Name = "Penny",
                            Title = "寫手"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
